In [7]:
import pandas as pd

file_path = "../data/raw/Online Retail.xlsx"

df = pd.read_excel(file_path)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [2]:
df.shape

(541909, 8)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(5268)

In [6]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9288)

In [7]:
cancelled = df[df["InvoiceNo"].astype(str).str.startswith("C")]

cancelled.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [8]:
cancelled[["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]].head(10)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
141,C536379,D,Discount,-1,27.50,14527.0
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,4.65,15311.0
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1.65,17548.0
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,0.29,17548.0
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,0.29,17548.0
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,0.29,17548.0
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,3.45,17548.0
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,1.65,17548.0
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,1.65,17548.0
939,C536506,22960,JAM MAKING SET WITH JARS,-6,4.25,17897.0

In [9]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [10]:
(df["UnitPrice"] <= 0).sum()

np.int64(2517)

In [11]:
zero_price = df[df["UnitPrice"] <= 0]

zero_price[[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "UnitPrice",
    "CustomerID"
]].head(20)

     InvoiceNo StockCode Description  Quantity  UnitPrice  CustomerID
622     536414     22139         NaN        56        0.0         NaN
1970    536545     21134         NaN         1        0.0         NaN
1971    536546     22145         NaN         1        0.0         NaN
1972    536547     37509         NaN         1        0.0         NaN
1987    536549    85226A         NaN         1        0.0         NaN
1988    536550     85044         NaN         1        0.0         NaN
2024    536552     20950         NaN         1        0.0         NaN
2025    536553     37461         NaN         3        0.0         NaN
2026    536554     84670         NaN        23        0.0         NaN
2406    536589     21777         NaN       -10        0.0         NaN
4347    536764    84952C         NaN       -38        0.0         NaN
4348    536765    84952C         NaN        19        0.0         NaN
6391    536941     22734      amazon        20        0.0         NaN
6392    536942     22139      amazon        15        0.0         NaN
7187    536995     35951         NaN        57        0.0         NaN
7188    536996     22712         NaN       -20        0.0         NaN
7189    536997     22028         NaN       -20        0.0         NaN
7190    536998     85067         NaN        -6        0.0         NaN
7191    536999     21421         NaN       110        0.0         NaN
7192    537000     21414         NaN       -22        0.0         NaN

In [12]:
df["CustomerID"].isna().mean() * 100

np.float64(24.926694334288598)

In [13]:
df["CustomerID"].nunique()

4372

In [6]:
df["transaction_type"].value_counts()

transaction_type
SALE      527390
RETURN      9251
Name: count, dtype: int64

In [1]:
import sys
sys.path.append("..")

from etl.test_read import extract_data
from etl.transform import transform_data

df = extract_data()
df = transform_data(df)

df["transaction_type"].value_counts()

Successfully extracted 541,909 rows.

transaction_type
SALE      527390
RETURN      9251
Name: count, dtype: int64

In [2]:
df[df["unitprice"] <= 0][
    [
        "invoiceno",
        "stockcode",
        "description",
        "quantity",
        "unitprice",
        "customerid",
        "transaction_type"
    ]
].head(20)

,invoiceno,stockcode,description,quantity,unitprice,customerid,transaction_type
622,536414,22139,NaN,56,0.0,<NA>,SALE
1970,536545,21134,NaN,1,0.0,<NA>,SALE
1971,536546,22145,NaN,1,0.0,<NA>,SALE
1972,536547,37509,NaN,1,0.0,<NA>,SALE
1987,536549,85226A,NaN,1,0.0,<NA>,SALE
1988,536550,85044,NaN,1,0.0,<NA>,SALE
2024,536552,20950,NaN,1,0.0,<NA>,SALE
2025,536553,37461,NaN,3,0.0,<NA>,SALE
2026,536554,84670,NaN,23,0.0,<NA>,SALE
2406,536589,21777,NaN,-10,0.0,<NA>,SALE
4347,536764,84952C,NaN,-38,0.0,<NA>,SALE
4348,536765,84952C,NaN,19,0.0,<NA>,SALE
6391,536941,22734,amazon,20,0.0,<NA>,SALE
6392,536942,22139,amazon,15,0.0,<NA>,SALE
7187,536995,35951,NaN,57,0.0,<NA>,SALE
7188,536996,22712,NaN,-20,0.0,<NA>,SALE
7189,536997,22028,NaN,-20,0.0,<NA>,SALE
7190,536998,85067,NaN,-6,0.0,<NA>,SALE
7191,536999,21421,NaN,110,0.0,<NA>,SALE
7192,537000,21414,NaN,-22,0.0,<NA>,SALE

In [3]:
df[df["unitprice"] <= 0]["description"].value_counts(dropna=False).head(20)

description
NaN                                1454
check                               159
?                                    47
damages                              45
damaged                              43
found                                25
sold as set on dotcom                20
adjustment                           16
Damaged                              14
FRENCH BLUE METAL DOOR SIGN 1         9
thrown away                           9
Unsaleable, destroyed.                9
amazon                                8
FRENCH BLUE METAL DOOR SIGN 8         8
Found                                 8
FRENCH BLUE METAL DOOR SIGN 4         7
FRENCH BLUE METAL DOOR SIGN No        7
OWL DOORSTOP                          7
FRENCH BLUE METAL DOOR SIGN 3         7
RECIPE BOX PANTRY YELLOW DESIGN       7
Name: count, dtype: int64

In [4]:
df[(df["unitprice"] <= 0) & (df["customerid"].notna())].shape[0]

40

In [5]:
df["description"].isna().sum()

np.int64(1454)

In [8]:
df = extract_data()
df = transform_data(df)

Successfully extracted 541,909 rows.

In [10]:
import importlib
import etl.transform

importlib.reload(etl.transform)

from etl.transform import transform_data

df = extract_data()
df = transform_data(df)

df["is_valid_sale"].value_counts()

Successfully extracted 541,909 rows.

is_valid_sale
True     392692
False    143949
Name: count, dtype: int64

In [11]:
sales_df = df[df["is_valid_sale"]].copy()

In [12]:
sales_df.shape

(392692, 11)

In [13]:
sales_df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,revenue,transaction_type,is_valid_sale
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,SALE,True
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,SALE,True
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,SALE,True
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,SALE,True
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,SALE,True

In [14]:
from pathlib import Path

output_path = Path("../data/processed/sales.csv")

output_path.parent.mkdir(parents=True, exist_ok=True)

sales_df.to_csv(output_path, index=False)

print(f"Saved {len(sales_df):,} rows to {output_path}")

Saved 392,692 rows to ..\data\processed\sales.csv

In [15]:
processed_df = pd.read_csv("../data/processed/sales.csv")

print("Shape:", processed_df.shape)
print("\nMissing values:")
print(processed_df.isna().sum())

Shape: (392692, 11)

Missing values:
invoiceno           0
stockcode           0
description         0
quantity            0
invoicedate         0
unitprice           0
customerid          0
country             0
revenue             0
transaction_type    0
is_valid_sale       0
dtype: int64